### ISSUE TITLE
[Help] How to use it?

### ISSUE THREAD

**Issue by FengLing02** [miscord-dev/palog#11]
Hi,
I'm using Linux server, which directory should I put this binary in?

**Comment by tsuzu** [comment]
@FengLing02 
Hi!
I added the installation guide https://github.com/miscord-dev/palog#usage
Check it and give me a feedback!
palog only depends on RCON, so you can put the binary anywhere.

**Comment by tsuzu** [comment]
If you still have concerns, create a new issue.
